[project]
name = "marketoracle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.26.0",
    "torch>=2.6.0",
    "pytorch-lightning>=2.5.0.post0",
    "mlflow>=2.21.3",
    "wandb>=0.19.9",
    "tinkoff-investments>=0.2.0b111",
    "lightning>=2.5.1",
    "scikit-learn>=1.6.1",
    "statsmodels>=0.14.4",
    "plotly==5.24.1",
    "pmdarima>=2.0.4",
    "prophet>=1.1.6",
    "catboost>=1.2.8",
    "aiogram>=3.20.0.post0",
    "aiohttp>=3.11.14",
    "apimoex>=1.4.0",
    "dotenv>=0.9.9",
    "investpy>=1.0.8",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "kaleido==0.2.1",
    "markdown>=3.8",
    "openai>=1.78.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "tradingview-ta>=3.3.0",
    "yandex-cloud-ml-sdk>=0.3.0",
    "yfinance>=0.2.36",
    "rich>=14.0.0",
]

[dependency-groups]
dev = [
    "fire>=0.7.0",
    "pre-commit>=4.2.0",
    "dvc>=3.59.1",
    "dvc-webdav>=3.0.0",
    "nbformat>=5.10.4",
]

[tool.setuptools]
packages = ["market_oracle_lib"]
