precision: 32
max_epochs: 5
accumulate_grad_batches: 1
val_check_interval: 1.0
overfit_batches: 0
num_sanity_val_steps: 4
deterministic: false
benchmark: false
gradient_clip_val: 2.0
log_every_n_steps: 1
detect_anomaly: false
enable_checkpointing: true
